version: "3"
services:
  server:
    build:
      context: .
    container_name: server
    ports:
      - "8080:8080"
    volumes:
      - ".:/app"
      - "/app/node_modules"
    environment:
      - NODE_ENV=development
    networks:
      - default