replicaCount: 3

image: ghcr.io/chia-network/cat1-balance

imagePullSecrets:
  - name: cat1-balance-image-pull

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 9090
  portName: http

deployCert: true

ingress:
  hostname: cat1.chia.net
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
  servicePort: http
  tls:
    enabled: true
    secretName: cat1-balance-star-tls

nameOverride: ""
fullnameOverride: ""

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
