replicaCount: 1

image: ghcr.io/chia-network/cat1-balance

imagePullSecrets:
  - name: cat1-balance-image-pull

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 9090
  portName: http

deployCert: true

ingress:
  hostname: cat1.chia.net
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8,100.64.0.0/10
    nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8,100.64.0.0/10
  servicePort: http
  tls:
    enabled: true
    secretName: cat1-balance-star-tls

nameOverride: ""
fullnameOverride: ""

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
